### ISSUE TITLE
Consider deprecating push-to-git.sh

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/contrib-toolbox#10]
Following on from issue #9 (and superceding it), [TravisCI now supports gh-pages publishing out of the box](https://docs.travis-ci.com/user/deployment/pages/), and it's a lot smoother than the `push-to-git.sh` script (as can be seen in [this example](https://github.com/symphonyoss/clj-symphony/blob/master/.travis.yml)).

I'd suggest that we deprecate `push-to-git.sh` and switch to the TravisCI approach going forward.

**Comment by maoo** [comment]
Thanks for the issue @pmonks . Currently, `push-to-git.sh` is not only used for Github Pages, as it is used also to push different contents (not only pages) and to different servers (ie GitLab).

I'll try to adopt Travis CI `pages` deployment as much as possible, though I don't think we'll be able to completely deprecate the script.

**Comment by pmonks** [comment]
Makes sense.  Let's at least switch off it for `gh-pages` publication.
